name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou_db"
database_id = "4ff9c13e-35a0-4520-b673-3396d5203b28"

[version_metadata]
binding = "CF_VERSION_METADATA"
